'use server';

/**
 * @fileOverview An AI agent for predictive maintenance advice based on vehicle maintenance records.
 *
 * - getPredictiveMaintenanceAdvice - A function that retrieves predictive maintenance advice for a vehicle.
 * - PredictiveMaintenanceAdviceInput - The input type for the getPredictiveMaintenanceAdvice function.
 * - PredictiveMaintenanceAdviceOutput - The return type for the getPredictiveMaintenanceAdvice function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PredictiveMaintenanceAdviceInputSchema = z.object({
  vehicleId: z.string().describe('The unique identifier of the vehicle.'),
  maintenanceRecords: z.string().describe('JSON string containing an array of maintenance records for the vehicle.'),
});
export type PredictiveMaintenanceAdviceInput = z.infer<typeof PredictiveMaintenanceAdviceInputSchema>;

const PredictiveMaintenanceAdviceOutputSchema = z.object({
  advice: z.string().describe('The predictive maintenance advice generated by the AI.'),
});
export type PredictiveMaintenanceAdviceOutput = z.infer<typeof PredictiveMaintenanceAdviceOutputSchema>;

export async function getPredictiveMaintenanceAdvice(
  input: PredictiveMaintenanceAdviceInput
): Promise<PredictiveMaintenanceAdviceOutput> {
  return predictiveMaintenanceAdvisorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'predictiveMaintenanceAdvisorPrompt',
  input: {schema: PredictiveMaintenanceAdviceInputSchema},
  output: {schema: PredictiveMaintenanceAdviceOutputSchema},
  prompt: `You are an AI assistant that analyzes vehicle maintenance records to provide predictive maintenance advice.

  Your goal is to identify potential issues such as recurring problems, parts that need more frequent monitoring or replacement than expected, and whether torque checks are performed as scheduled.
  Based on the maintenance history, provide a concise summary of potential issues and recommended actions.

  Vehicle ID: {{{vehicleId}}}
  Maintenance Records: {{{maintenanceRecords}}}
  \n  Provide your predictive maintenance advice below:
  `,
});

const predictiveMaintenanceAdvisorFlow = ai.defineFlow(
  {
    name: 'predictiveMaintenanceAdvisorFlow',
    inputSchema: PredictiveMaintenanceAdviceInputSchema,
    outputSchema: PredictiveMaintenanceAdviceOutputSchema,
  },
  async input => {
    try {
      // Parse the maintenance records string into a JSON object
      JSON.parse(input.maintenanceRecords);
    } catch (e) {
      throw new Error(
        'Invalid JSON format for maintenance records: ' + input.maintenanceRecords
      );
    }

    const {output} = await prompt(input);
    return output!;
  }
);
